# Generated by Django 4.2 on 2024-03-30 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nonStim', models.BooleanField(default=False)),
                ('totalServings', models.PositiveIntegerField()),
                ('sizeInOz', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredientName', models.CharField(max_length=100)),
                ('dosage', models.PositiveIntegerField()),
                ('pre_workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='customer_app.preworkout')),
            ],
        ),
    ]
