# Generated by Django 4.2 on 2024-04-08 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preworkout',
            name='reviewOutOfFive',
            field=models.PositiveIntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=3),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
